### ISSUE TITLE
How to upgrade to V1.1.1[**MANDATORY Upgrade**]

### ISSUE THREAD

**Issue by Normalnoise** [swanchain/go-computing-provider#210]
# Steps to Upgrade to CP Version 1.1.1
## Introduction

This document provides the steps to upgrade to the new version based on your role. Both new and existing users can follow this guide.

## As an ECP:

1. Export and back up your private key:

    ```bash
    export CP_PATH="<YOUR_CP_PATH>"
    computing-provider wallet export <YOUR_WALLET_ADDRESS> 
    ```
2. Upgrade `resource-exporter` to v12.0.0

    - Delete  container `resource-exporter` and `filswan/resource-exporter` local image
   ```
   docker rm -f resource-exporter
   docker rmi -f filswan/resource-exporter:v11.3.2
   ```
    -  CP will automatically pull the image and run the resource-exporter container

3. Use the latest CP version to run CP
    - Download the latest CP binary:
   ```
   wget https://github.com/swanchain/go-computing-provider/releases/download/v1.1.1/computing-provider
   ```
    - Follow the [Deployment Documentation](https://github.com/swanchain/go-computing-provider/blob/releases/ubi/README.md) to start.

---

## As an FCP:

1. Back up and export the private key:

    ```bash
    export CP_PATH="<YOUR_CP_PATH>"
    computing-provider wallet export <YOUR_WALLET_ADDRESS>
    ```

2. Modify the `config.toml` file in the `$CP_PATH` directory:
    - 🔴 **Critical:** You **MUST** update the `[HUB].OrchestratorPk`, or you will not get the task any more.

   ```
   [HUB]
   OrchestratorPk = "0xd875bD44158208fD0FDD46729Aab6709f62C7821"    
   ```

3. **Upgrade `resource-exporter` to v12.0.0**

    - Stop the computing-provider service.
    - Delete component `resource-exporter` and `filswan/resource-exporter` local image
      ```
      kubectl delete ds -n kube-system resource-exporter-ds

      docker rmi -f filswan/resource-exporter:v11.3.2
      ```
    - Reinstall `resource-exporter` by the command:
      ```
      cat <<EOF | kubectl apply -f -
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        namespace: kube-system
        name: resource-exporter-ds
        labels:
          app: resource-exporter
      spec:
        selector:
          matchLabels:
            app: resource-exporter
        template:
          metadata:
            labels:
              app: resource-exporter
          spec:
            containers:
              - name: resource-exporter
                image: filswan/resource-exporter:v12.0.0
                imagePullPolicy: IfNotPresent
                securityContext:
                  privileged: true
                volumeMounts:
                  - name: machine-id
                    mountPath: /etc/machine-id
                    readOnly: true
            volumes:
              - name: machine-id
                hostPath:
                  path: /etc/machine-id
                  type: File
      EOF
      ```
   
    - Check the `resource-exporter` version:
      ```
      kubectl describe po -n kube-system resource-exporter-ds |grep "Image:"
      ```
      It should be:
      ```
      Image:          filswan/resource-exporter:v12.0.0
      ```

and ensure it is running by `kubectl get po -n kube-system`
<img width="650" alt="image" src="https://github.com/user-attachments/assets/7a974ae8-e82d-46b6-ac4e-70797c09f959">

1. Use the latest CP version(v1.1.1) to run CP
    - Download the latest CP binary:
   ```
   wget https://github.com/swanchain/go-computing-provider/releases/download/v1.1.1/computing-provider
   ```

    - Follow the [Deployment DOC](https://github.com/swanchain/go-computing-provider/blob/release-v1.1.0/README.md#initialization-cp-account) to start.

5. Check your CP version
   The minimal CP version should be `v1.1.1`
   ```
   computing-provider -v
   ```

## Recommended Actions:
All CPs must complete this mandatory upgrade by **2:00 AM (UTC+0) on February 12, 2025**.
