### ISSUE TITLE
Upgrade to CP V0.5.0

### ISSUE THREAD

**Issue by Normalnoise** [swanchain/go-computing-provider#89]
# Steps to Upgrade to CP Version 0.5.0:

## As an ECP:

1. Export and back up your private key:

    ```bash
    export CP_PATH="<YOUR_CP_PATH>"
    computing-provider wallet export <YOUR_WALLET_ADDRESS> 
    ```

2. Back up the `config.toml` file in the `$CP_PATH` directory as `config.toml.bak`.
	```
	mv config.toml config.toml.bak
	```
3. Follow the [Deployment DOC](https://github.com/swanchain/go-computing-provider/blob/release-v0.5.0/ubi/README.md) to start.

---

## As an FCP:

1. Withdraw your previous staked Swan-ETH:

    ```bash
    computing-provider collateral withdraw <YOUR_WALLET_ADDRESS> <AMOUNT>
    ```

2. Back up and export the private key:

    ```bash
    export CP_PATH="<YOUR_CP_PATH>"
    computing-provider wallet export <YOUR_WALLET_ADDRESS>
    ```

3. Modify the `config.toml` file in the `$CP_PATH` directory:

    ```toml
    [CONTRACT]
    SWAN_CONTRACT = "0x91B25A65b295F0405552A4bbB77879ab5e38166c"              # Swan token's contract address
    SWAN_COLLATERAL_CONTRACT = "0xC7980d5a69e8AA9797934aCf18e483EB4C986e01"   # Swan's collateral address
    REGISTER_CP_CONTRACT = "0x6EDf891B53ba2c6Fade6Ae373682ED48dEa5AF48"       # The CP registration contract address
    ZK_COLLATERAL_CONTRACT = "0x1d2557C9d14882D9eE291BB66eaC6c1C4a587054"     # The ZK task's collateral contract address
    ```

4. Follow the [Deployment DOC](https://github.com/swanchain/go-computing-provider/blob/release-v0.5.0/README.md#initialization-cp-account) to start.

> **Note**: If you found too many resource are used, you can release your CP resources by running
> ```
> kubectl get namespaces | awk '/^ns-/{print $1}' | xargs kubectl delete namespace
> ```

5. Check your CP version
the minimal CP version should be `v0.5.0`
```
computing-provider -v
```
